Repository MaiQuocHuy/javaspringboot-course-project, pull requests merged in 2025-09, with the labels that each got.

#87 feat: Add user permissions management and role assignment APIs
  docs/API_User_Permissions_Test.md
  springboot-app/src/main/java/project/ktc/springboot_app/permission/controllers/UserPermissionController.java
  springboot-app/src/main/java/project/ktc/springboot_app/permission/dto/UserPermissionsDto.java
  springboot-app/src/main/java/project/ktc/springboot_app/permission/services/AuthorizationService.java
  springboot-app/src/main/java/project/ktc/springboot_app/user/controllers/AdminUserController.java
  springboot-app/src/main/java/project/ktc/springboot_app/user/dto/AssignUserRoleRequest.java
  springboot-app/src/main/java/project/ktc/springboot_app/user/dto/UpdateUserRoleDto.java
  springboot-app/src/main/java/project/ktc/springboot_app/user/dto/UserWithRoleDto.java
  springboot-app/src/main/java/project/ktc/springboot_app/user/interfaces/UserService.java
  springboot-app/src/main/java/project/ktc/springboot_app/user/services/UserServiceImp.java
Labels: Possible security concern, Review effort 3/5

#91 feat: Add asynchronous certificate creation and processing functionality
  springboot-app/src/main/java/project/ktc/springboot_app/certificate/controllers/CertificateController.java
  springboot-app/src/main/java/project/ktc/springboot_app/certificate/interfaces/CertificateService.java
  springboot-app/src/main/java/project/ktc/springboot_app/certificate/repositories/CertificateRepository.java
  springboot-app/src/main/java/project/ktc/springboot_app/certificate/services/CertificateServiceImp.java
  springboot-app/test_discount_null_validation.java
Labels: Review effort 3/5

#92 feat: Update affiliate commission percentage and discount values; add…
  springboot-app/src/main/java/project/ktc/springboot_app/discount/config/AffiliateConfig.java
  springboot-app/src/main/java/project/ktc/springboot_app/discount/services/DiscountServiceImp.java
  springboot-app/src/main/java/project/ktc/springboot_app/payment/service/AdminPaymentServiceImpl.java
  springboot-app/src/main/java/project/ktc/springboot_app/utils/Constants.java
  springboot-app/src/main/java/project/ktc/springboot_app/utils/ExtractPaymentDetailFromSessionId.java
  springboot-app/src/main/resources/application.properties
Labels: Possible security concern, Review effort 2/5

#93 feat: Add endpoint to retrieve all courses without pagination
  springboot-app/src/main/java/project/ktc/springboot_app/chat/controllers/ChatMessageController.java
  springboot-app/src/main/java/project/ktc/springboot_app/chat/dtos/AsyncMessageStatusEvent.java
  springboot-app/src/main/java/project/ktc/springboot_app/chat/dtos/AsyncSendMessageRequest.java
  springboot-app/src/main/java/project/ktc/springboot_app/chat/dtos/ChatMessageResponse.java
  springboot-app/src/main/java/project/ktc/springboot_app/chat/dtos/SimpleChatMessageResponse.java
  springboot-app/src/main/java/project/ktc/springboot_app/chat/repositories/ChatMessageRepository.java
  springboot-app/src/main/java/project/ktc/springboot_app/chat/services/ChatMessageServiceImp.java
  springboot-app/src/main/java/project/ktc/springboot_app/course/controllers/InstructorCourseController.java
  springboot-app/src/main/java/project/ktc/springboot_app/course/controllers/StudentCourseController.java
  springboot-app/src/main/java/project/ktc/springboot_app/course/interfaces/InstructorCourseService.java
  springboot-app/src/main/java/project/ktc/springboot_app/course/repositories/InstructorCourseRepository.java
  springboot-app/src/main/java/project/ktc/springboot_app/course/services/InstructorCourseServiceImp.java
  springboot-app/src/main/java/project/ktc/springboot_app/enrollment/interfaces/EnrollmentService.java
  springboot-app/src/main/java/project/ktc/springboot_app/enrollment/repositories/EnrollmentRepository.java
  springboot-app/src/main/java/project/ktc/springboot_app/enrollment/services/EnrollmentServiceImp.java
Labels: Review effort 3/5

#94 fix: Update username validation regex and example in AdminCreateUserDto
  springboot-app/src/main/java/project/ktc/springboot_app/user/dto/AdminCreateUserDto.java
Labels: Review effort 2/5

#106 feat: Add 'type' field to discount DTOs for enhanced discount infor
  springboot-app/src/main/java/project/ktc/springboot_app/discount/controllers/InstructorDiscountController.java
  springboot-app/src/main/java/project/ktc/springboot_app/discount/dto/InstructorAffiliatePayoutResponseDto.java
  springboot-app/src/main/java/project/ktc/springboot_app/discount/dto/InstructorDiscountUsageResponseDto.java
  springboot-app/src/main/java/project/ktc/springboot_app/discount/dto/StudentAffiliatePayoutResponseDto.java
  springboot-app/src/main/java/project/ktc/springboot_app/discount/dto/StudentDiscountUsageResponseDto.java
  springboot-app/src/main/java/project/ktc/springboot_app/discount/interfaces/InstructorAffiliatePayoutService.java
  springboot-app/src/main/java/project/ktc/springboot_app/discount/interfaces/InstructorDiscountUsageService.java
  springboot-app/src/main/java/project/ktc/springboot_app/discount/repositories/InstructorAffiliatePayoutRepository.java
  springboot-app/src/main/java/project/ktc/springboot_app/discount/repositories/InstructorDiscountUsageRepository.java
  springboot-app/src/main/java/project/ktc/springboot_app/discount/services/InstructorAffiliatePayoutServiceImp.java
  springboot-app/src/main/java/project/ktc/springboot_app/discount/services/InstructorDiscountUsageServiceImp.java
Labels: Review effort 3/5

#107 feat: Add endpoint to retrieve available public discount codes
  springboot-app/src/main/java/project/ktc/springboot_app/discount/controllers/CommonDiscountController.java
  springboot-app/src/main/java/project/ktc/springboot_app/discount/dto/DiscountResponseDto.java
  springboot-app/src/main/java/project/ktc/springboot_app/discount/interfaces/DiscountService.java
  springboot-app/src/main/java/project/ktc/springboot_app/discount/repositories/DiscountRepository.java
  springboot-app/src/main/java/project/ktc/springboot_app/discount/services/DiscountServiceImp.java
Labels: Review effort 3/5

#108 feat: Implement APIs for Student Dashboard page
  springboot-app/src/main/java/project/ktc/springboot_app/course/controllers/StudentCourseController.java
  springboot-app/src/main/java/project/ktc/springboot_app/enrollment/dto/StudentActivityDto.java
  springboot-app/src/main/java/project/ktc/springboot_app/enrollment/dto/StudentDashboardStatsDto.java
  springboot-app/src/main/java/project/ktc/springboot_app/enrollment/interfaces/EnrollmentService.java
  springboot-app/src/main/java/project/ktc/springboot_app/enrollment/repositories/EnrollmentRepository.java
  springboot-app/src/main/java/project/ktc/springboot_app/enrollment/services/EnrollmentServiceImp.java
  springboot-app/src/main/java/project/ktc/springboot_app/lesson/repositories/LessonCompletionRepository.java
  springboot-app/src/main/java/project/ktc/springboot_app/quiz/repositories/QuizResultRepository.java
Labels: Review effort 3/5

#111 feat: Done notification fearture
  springboot-app/src/main/java/project/ktc/springboot_app/instructor_application/services/InstructorApplicationServiceImp.java
  springboot-app/src/main/java/project/ktc/springboot_app/notification/controllers/NotificationsController.java
  springboot-app/src/main/java/project/ktc/springboot_app/notification/dto/CreateNotificationDto.java
  springboot-app/src/main/java/project/ktc/springboot_app/notification/dto/NotificationDto.java
  springboot-app/src/main/java/project/ktc/springboot_app/notification/dto/NotificationResponseDto.java
  springboot-app/src/main/java/project/ktc/springboot_app/notification/entity/Notification.java
  springboot-app/src/main/java/project/ktc/springboot_app/notification/interfaces/NotificationService.java
  springboot-app/src/main/java/project/ktc/springboot_app/notification/repositories/NotificationRepository.java
  springboot-app/src/main/java/project/ktc/springboot_app/notification/services/NotificationServiceImp.java
  springboot-app/src/main/java/project/ktc/springboot_app/notification/utils/NotificationHelper.java
  springboot-app/src/main/java/project/ktc/springboot_app/stripe/services/StripeWebhookService.java
  springboot-app/src/main/resources/db/changelog/changes/100-new-schema-complete.xml
  springboot-app/src/main/resources/db/changelog/changes/158-seed-notification.xml
Labels: Possible security concern, Review effort 3/5

#112 feat: Implement APIs to get statistics for Student Portal
  springboot-app/src/main/java/project/ktc/springboot_app/payment/controllers/StudentPaymentController.java
  springboot-app/src/main/java/project/ktc/springboot_app/payment/dto/StudentPaymentStatsDto.java
  springboot-app/src/main/java/project/ktc/springboot_app/payment/interfaces/PaymentService.java
  springboot-app/src/main/java/project/ktc/springboot_app/payment/repositories/PaymentRepository.java
  springboot-app/src/main/java/project/ktc/springboot_app/payment/services/PaymentServiceImp.java
  springboot-app/src/main/java/project/ktc/springboot_app/quiz/controllers/StudentQuizController.java
  springboot-app/src/main/java/project/ktc/springboot_app/quiz/dto/StudentQuizStatsDto.java
  springboot-app/src/main/java/project/ktc/springboot_app/quiz/interfaces/StudentQuizService.java
  springboot-app/src/main/java/project/ktc/springboot_app/quiz/repositories/QuizResultRepository.java
  springboot-app/src/main/java/project/ktc/springboot_app/quiz/services/StudentQuizServiceImp.java
  springboot-app/src/main/java/project/ktc/springboot_app/review/controllers/StudentReviewController.java
  springboot-app/src/main/java/project/ktc/springboot_app/review/dto/StudentReviewStatsDto.java
  springboot-app/src/main/java/project/ktc/springboot_app/review/interfaces/ReviewService.java
  springboot-app/src/main/java/project/ktc/springboot_app/review/repositories/ReviewRepository.java
  springboot-app/src/main/java/project/ktc/springboot_app/review/services/ReviewServiceImp.java
Labels: Review effort 2/5

#117 Create Admin Reveneu Management API
  springboot-app/src/main/java/project/ktc/springboot_app/instructor_student/controller/InstructorStudentController.java
  springboot-app/src/main/java/project/ktc/springboot_app/payment/dto/SampleDataGenerationDTO.java
  springboot-app/src/main/java/project/ktc/springboot_app/payment/entity/Payment.java
  springboot-app/src/main/java/project/ktc/springboot_app/payment/interfaces/PaymentDataGenerationService.java
  springboot-app/src/main/java/project/ktc/springboot_app/payment/services/PaymentDataGenerationServiceImpl.java
  springboot-app/src/main/java/project/ktc/springboot_app/quiz/controllers/InstructorQuizController.java
  springboot-app/src/main/java/project/ktc/springboot_app/revenue/controllers/AdminRevenueController.java
  springboot-app/src/main/java/project/ktc/springboot_app/revenue/dto/ComparativeAnalysisDTO.java
  springboot-app/src/main/java/project/ktc/springboot_app/revenue/dto/MonthlyRevenueDTO.java
  springboot-app/src/main/java/project/ktc/springboot_app/revenue/dto/PerformanceMetricsDTO.java
  springboot-app/src/main/java/project/ktc/springboot_app/revenue/dto/SeasonalHeatmapDTO.java
  springboot-app/src/main/java/project/ktc/springboot_app/revenue/dto/StatisticsDTO.java
  springboot-app/src/main/java/project/ktc/springboot_app/revenue/dto/TopSpendersDTO.java
  springboot-app/src/main/java/project/ktc/springboot_app/revenue/interfaces/AdminRevenueService.java
  springboot-app/src/main/java/project/ktc/springboot_app/revenue/repositories/AdminRevenueRepository.java
  springboot-app/src/main/java/project/ktc/springboot_app/revenue/services/AdminRevenueServiceImpl.java
Labels: Review effort 4/5
