Repository MaiQuocHuy/javaspringboot-course-project, pull requests merged in 2025-08, with the labels that each got.

#23 feat: Update environment configuration and enhance payment status retrieval functionality
  springboot-app/.env.local
  springboot-app/pom.xml
  springboot-app/src/main/java/project/ktc/springboot_app/payment/interfaces/PaymentService.java
  springboot-app/src/main/java/project/ktc/springboot_app/payment/service/PaymentServiceImp.java
  springboot-app/src/main/java/project/ktc/springboot_app/stripe/controllers/StripeController.java
  springboot-app/src/main/java/project/ktc/springboot_app/stripe/dto/PaymentStatusResponse.java
  springboot-app/src/main/java/project/ktc/springboot_app/stripe/services/StripeCheckoutService.java
Labels: Possible security concern, Review effort 2/5

#34 Add SMTP email configuration to .env.local
  springboot-app/.env.local
  springboot-app/src/main/java/project/ktc/springboot_app/email/controllers/EmailController.java
Labels: Review effort 1/5

#36 feat: Implement payment confirmation email functionality and add course reviews retrieval by slug
  springboot-app/.github/instructions/task_list.instructions.md
  springboot-app/src/main/java/project/ktc/springboot_app/course/dto/CourseReviewFilterDto.java
  springboot-app/src/main/java/project/ktc/springboot_app/course/repositories/CourseRepository.java
  springboot-app/src/main/java/project/ktc/springboot_app/email/interfaces/EmailService.java
  springboot-app/src/main/java/project/ktc/springboot_app/email/services/EmailServiceImp.java
  springboot-app/src/main/java/project/ktc/springboot_app/review/controllers/ReviewController.java
  springboot-app/src/main/java/project/ktc/springboot_app/review/interfaces/ReviewService.java
  springboot-app/src/main/java/project/ktc/springboot_app/review/repositories/ReviewRepository.java
  springboot-app/src/main/java/project/ktc/springboot_app/review/services/ReviewServiceImp.java
  springboot-app/src/main/java/project/ktc/springboot_app/stripe/services/StripeWebhookService.java
  springboot-app/src/main/resources/application-email.yml
  springboot-app/src/main/resources/application.properties
  springboot-app/src/main/resources/templates/email/payment-confirmation-template.html
Labels: Review effort 3/5

#41 feat: Add instructor overview statistics and duplicate slug check in course services
  springboot-app/src/main/java/project/ktc/springboot_app/comment/controllers/CommentController.java
  springboot-app/src/main/java/project/ktc/springboot_app/course/dto/CourseDetailResponseDto.java
  springboot-app/src/main/java/project/ktc/springboot_app/course/repositories/CourseRepository.java
  springboot-app/src/main/java/project/ktc/springboot_app/course/services/CourseServiceImp.java
  springboot-app/src/main/java/project/ktc/springboot_app/course/services/InstructorCourseServiceImp.java
  springboot-app/src/main/java/project/ktc/springboot_app/utils/MathUtil.java
  springboot-app/src/main/java/project/ktc/springboot_app/utils/StringUtil.java
Labels: Review effort 2/5
